"""
schemas/cancellation.py
-----------------------
Pydantic v2 schema for a booking cancellation request.

Design intent
-------------
CancellationRequest captures only what the passenger supplies directly.
The reason_category field (generated by the NLP component) is intentionally
absent; it will be added in a later phase once NLP integration is implemented.

Phase 1 note
------------
No refund calculation, business-rule evaluation, or database operations are
performed here.  Pure data validation only.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class CancellationRequest(BaseModel):
    """
    Cancellation request submitted by the passenger.

    Attributes
    ----------
    booking_reference: The unique reference code for the booking to cancel.
    reason:            Free-text reason provided by the passenger
                       (3–1 000 characters).
    """

    booking_reference: str = Field(
        ...,
        min_length=1,
        description="Unique booking reference to cancel",
    )
    reason: str = Field(
        ...,
        min_length=3,
        max_length=1000,
        description="Passenger-supplied cancellation reason (3–1 000 chars)",
    )

    model_config = {"str_strip_whitespace": True}
