"""
cancellation/rag.py
-------------------
RAG Policy Knowledge Base & Retrieval Component for RailSense AI.

Features:
1. Dense Vector Retrieval via Supabase pgvector:
   - Uses 384-dimensional normalized dense vectors generated by SentenceTransformer ('all-MiniLM-L6-v2').
   - Queries cancellation_policy_embeddings in Supabase PostgreSQL using cosine distance operator (<=>).
   - High semantic relevance for complex passenger queries (e.g., duplicate charges, delays, emergencies).
2. Deterministic In-Memory TF-IDF Fallback:
   - Chunked articles with formal citations from policies/ (*.md).
   - Instantaneous, zero-external-dependency fallback when offline, in CI/pytest test suites,
     or when cloud database credentials are unavailable.
3. Strict Human-in-the-Loop Fact Grounding:
   - Returns top-k verified policy chunks with official citations (e.g., [POL-REF-003 - Article 2])
     to ground the Gemini LLM advisory briefing and human adjudicators.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path
from typing import Any

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sqlalchemy import text

# Ensure booking-agent root is in sys.path
_CURRENT_DIR = Path(__file__).resolve().parent
_BOOKING_AGENT_DIR = _CURRENT_DIR.parent
if str(_BOOKING_AGENT_DIR) not in sys.path:
    sys.path.insert(0, str(_BOOKING_AGENT_DIR))

from database.database import DATABASE_URL, engine, is_test_environment

_POLICIES_DIR = _CURRENT_DIR / "policies"
MODEL_NAME = "all-MiniLM-L6-v2"

# Lazy-loaded singletons
_embedding_model = None


def _get_embedding_model():
    """Lazy-load SentenceTransformer model to minimize startup overhead."""
    global _embedding_model
    if _embedding_model is None:
        from sentence_transformers import SentenceTransformer

        _embedding_model = SentenceTransformer(MODEL_NAME)
    return _embedding_model


def _search_supabase_pgvector(query: str, top_k: int = 3) -> list[dict[str, Any]] | None:
    """
    Execute semantic similarity search using Supabase pgvector.
    Returns list of matching chunks or None if unavailable/offline.
    """
    # Prefer local fallback in automated test mode to preserve speed and offline testability
    if is_test_environment() and os.getenv("USE_LIVE_DB") != "1":
        return None

    if DATABASE_URL.startswith("sqlite"):
        return None

    try:
        model = _get_embedding_model()
        query_vec = model.encode(query.strip(), normalize_embeddings=True).tolist()
        vec_str = f"[{','.join(f'{x:.6f}' for x in query_vec)}]"

        sql = text(
            """
            SELECT 
                id, 
                document, 
                document_id, 
                section, 
                citation, 
                content, 
                round(similarity::numeric, 4) AS similarity_score
            FROM match_cancellation_policies(CAST(:query_vec AS vector), :match_count);
            """
        )

        with engine.connect() as conn:
            rows = conn.execute(sql, {"query_vec": vec_str, "match_count": top_k}).fetchall()

        if not rows:
            return None

        results: list[dict[str, Any]] = []
        for r in rows:
            results.append(
                {
                    "document": r.document,
                    "document_id": r.document_id,
                    "section": r.section,
                    "citation": r.citation,
                    "content": r.content,
                    "similarity_score": float(r.similarity_score),
                    "retrieval_method": "supabase_pgvector",
                }
            )
        return results
    except Exception as exc:
        print(f"[RAG] Supabase pgvector search bypassed: {exc}")
        return None


class PolicyKnowledgeBase:
    """
    RAG Vector Store for RailSense AI Railway Policies with Supabase pgvector
    and local TF-IDF fallback.
    """

    def __init__(self, policies_dir: Path | None = None):
        self.policies_dir = policies_dir or _POLICIES_DIR
        self.chunks: list[dict[str, Any]] = []
        self.vectorizer: TfidfVectorizer | None = None
        self.tfidf_matrix = None
        self._load_and_index()

    def _load_and_index(self) -> None:
        """Read all markdown policy files, chunk by article/section, and build local TF-IDF index."""
        if not self.policies_dir.is_dir():
            return

        documents = sorted(list(self.policies_dir.glob("*.md")))
        corpus: list[str] = []

        for doc_path in documents:
            doc_name = doc_path.name
            with open(doc_path, "r", encoding="utf-8") as f:
                content = f.read()

            # Extract Document ID / Title if available
            doc_id_match = re.search(r"Document ID:\s*([A-Z0-9-]+)", content)
            doc_id = doc_id_match.group(1) if doc_id_match else doc_name.replace(".md", "").upper()

            # Split by markdown headers ## Article
            sections = re.split(r"(?=^##\s+)", content, flags=re.MULTILINE)
            for sec in sections:
                sec_text = sec.strip()
                if not sec_text:
                    continue

                lines = sec_text.splitlines()
                header = lines[0].replace("#", "").strip() if lines else "General Policy"

                # Build readable citation
                citation = f"[{doc_id} - {header}]"

                chunk_record = {
                    "document": doc_name,
                    "document_id": doc_id,
                    "section": header,
                    "content": sec_text,
                    "citation": citation,
                }
                self.chunks.append(chunk_record)
                corpus.append(f"{header}\n{sec_text}")

        if corpus:
            self.vectorizer = TfidfVectorizer(stop_words="english")
            self.tfidf_matrix = self.vectorizer.fit_transform(corpus)

    def retrieve(self, query: str, top_k: int = 3) -> list[dict[str, Any]]:
        """
        Retrieve the top-k most relevant policy chunks for a given query.
        Tries Supabase pgvector first; falls back to local TF-IDF cosine similarity.
        """
        clean_query = query.strip()
        if not clean_query:
            return []

        # 1. Primary: Cloud Supabase pgvector search
        pgvector_results = _search_supabase_pgvector(clean_query, top_k=top_k)
        if pgvector_results is not None and len(pgvector_results) > 0:
            return pgvector_results

        # 2. Resilient Fallback: Local TF-IDF Cosine Similarity
        if not self.chunks or self.vectorizer is None or self.tfidf_matrix is None:
            return []

        query_vec = self.vectorizer.transform([clean_query])
        sims = cosine_similarity(query_vec, self.tfidf_matrix).flatten()

        top_indices = sims.argsort()[::-1][:top_k]

        results: list[dict[str, Any]] = []
        for idx in top_indices:
            score = float(sims[idx])
            chunk = dict(self.chunks[idx])
            chunk["similarity_score"] = round(score, 4)
            chunk["retrieval_method"] = "local_tfidf"
            results.append(chunk)

        return results


# Module-level singleton instance
_kb_instance: PolicyKnowledgeBase | None = None


def get_policy_knowledge_base() -> PolicyKnowledgeBase:
    global _kb_instance
    if _kb_instance is None:
        _kb_instance = PolicyKnowledgeBase()
    return _kb_instance


def retrieve_relevant_policies(query: str, top_k: int = 3) -> list[dict[str, Any]]:
    """
    Public RAG function: returns top-k verified policy chunks for a cancellation query.
    """
    kb = get_policy_knowledge_base()
    return kb.retrieve(query, top_k=top_k)
