"""
cancellation/rag.py
-------------------
RAG Policy Knowledge Base & Retrieval Component for RailSense AI.

Features:
1. Dense Vector Retrieval via Supabase pgvector:
   - Uses 384-dimensional normalized dense vectors generated by SentenceTransformer ('all-MiniLM-L6-v2').
   - Queries cancellation_policy_embeddings in Supabase PostgreSQL using cosine distance operator (<=>).
   - High semantic relevance for complex passenger queries (e.g., duplicate charges, delays, emergencies).
2. Deterministic In-Memory TF-IDF Fallback:
   - Chunked articles with formal citations from policies/ (*.md).
   - Instantaneous, zero-external-dependency fallback when offline, in CI/pytest test suites,
     or when cloud database credentials are unavailable.
3. Strict Human-in-the-Loop Fact Grounding:
   - Returns top-k verified policy chunks with official citations (e.g., [POL-REF-003 - Article 2])
     to ground the Gemini LLM advisory briefing and human adjudicators.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path
from typing import Any

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sqlalchemy import text

# Ensure booking-agent root is in sys.path
_CURRENT_DIR = Path(__file__).resolve().parent
_BOOKING_AGENT_DIR = _CURRENT_DIR.parent
if str(_BOOKING_AGENT_DIR) not in sys.path:
    sys.path.insert(0, str(_BOOKING_AGENT_DIR))

from database.database import DATABASE_URL, engine, is_test_environment

_POLICIES_DIR = _CURRENT_DIR / "policies"
MODEL_NAME = "all-MiniLM-L6-v2"

# Lazy-loaded singletons
_embedding_model = None


def _get_embedding_model():
    """Lazy-load SentenceTransformer model to minimize startup overhead."""
    global _embedding_model
    if _embedding_model is None:
        from sentence_transformers import SentenceTransformer

        _embedding_model = SentenceTransformer(MODEL_NAME)
    return _embedding_model


def _search_supabase_pgvector(query: str, top_k: int = 3) -> list[dict[str, Any]] | None:
    """
    Execute semantic similarity search using Supabase pgvector.
    Returns list of matching chunks or None if unavailable/offline.
    """
    # Prefer local fallback in automated test mode to preserve speed and offline testability
    if is_test_environment() and os.getenv("USE_LIVE_DB") != "1":
        return None

    if os.getenv("USE_PGVECTOR") != "1":
        return None

    if DATABASE_URL.startswith("sqlite"):
        return None

    try:
        model = _get_embedding_model()
        query_vec = model.encode(query.strip(), normalize_embeddings=True).tolist()
        vec_str = f"[{','.join(f'{x:.6f}' for x in query_vec)}]"

        sql = text(
            """
            SELECT 
                id, 
                document, 
                document_id, 
                section, 
                citation, 
                content, 
                round(similarity::numeric, 4) AS similarity_score
            FROM match_cancellation_policies(CAST(:query_vec AS vector), :match_count);
            """
        )

        with engine.connect() as conn:
            rows = conn.execute(sql, {"query_vec": vec_str, "match_count": top_k}).fetchall()

        if not rows:
            return None

        results: list[dict[str, Any]] = []
        for r in rows:
            results.append(
                {
                    "document": r.document,
                    "document_id": r.document_id,
                    "section": r.section,
                    "citation": r.citation,
                    "content": r.content,
                    "similarity_score": float(r.similarity_score),
                    "retrieval_method": "supabase_pgvector",
                }
            )
        return results
    except Exception as exc:
        print(f"[RAG] Supabase pgvector search bypassed: {exc}")
        return None


class PolicyKnowledgeBase:
    """
    RAG Vector Store for RailSense AI Railway Policies with Supabase pgvector
    and local TF-IDF fallback.
    """

    def __init__(self, policies_dir: Path | None = None):
        self.policies_dir = policies_dir or _POLICIES_DIR
        self.chunks: list[dict[str, Any]] = []
        self.vectorizer: TfidfVectorizer | None = None
        self.tfidf_matrix = None
        self._load_and_index()

    def _load_and_index(self) -> None:
        """Read all markdown policy files, chunk by article/section, and build local TF-IDF index."""
        if not self.policies_dir.is_dir():
            return

        documents = sorted(list(self.policies_dir.glob("*.md")))
        corpus: list[str] = []

        for doc_path in documents:
            doc_name = doc_path.name
            with open(doc_path, "r", encoding="utf-8") as f:
                content = f.read()

            # Extract Document Metadata
            doc_id_match = re.search(r"Document ID:\s*([A-Z0-9-]+)", content)
            doc_id = doc_id_match.group(1) if doc_id_match else doc_name.replace(".md", "").upper()

            title_match = re.search(r"^#\s+([^\n]+)", content, flags=re.MULTILINE)
            doc_title = title_match.group(1).strip() if title_match else doc_name.replace(".md", "").replace("_", " ").title()

            domain_match = re.search(r"Domain:\s*([a-zA-Z_-]+)", content, flags=re.IGNORECASE)
            if domain_match:
                domain = domain_match.group(1).lower().strip()
            elif "sec" in doc_id.lower() or "security" in doc_name.lower():
                domain = "security"
            elif "canc" in doc_id.lower() or "cancellation" in doc_name.lower() or "refund" in doc_name.lower():
                domain = "cancellation"
            else:
                domain = "booking"

            status_match = re.search(r"Status:\s*([^\n]+)", content, flags=re.IGNORECASE)
            status_val = status_match.group(1).strip() if status_match else "ACTIVE (DEMO / ACADEMIC SPECIFICATION)"

            ver_match = re.search(r"Version:\s*([^\n]+)", content, flags=re.IGNORECASE)
            version_val = ver_match.group(1).strip() if ver_match else "v1.0"

            date_match = re.search(r"Effective Date:\s*([^\n]+)", content, flags=re.IGNORECASE)
            eff_date = date_match.group(1).strip() if date_match else "2026-01-01"

            # Split by markdown headers ## Article
            sections = re.split(r"(?=^##\s+)", content, flags=re.MULTILINE)
            art_idx = 1
            for sec in sections:
                sec_text = sec.strip()
                if not sec_text or sec_text.startswith("# DEMO") or sec_text.startswith("Document ID:"):
                    continue

                lines = sec_text.splitlines()
                header = lines[0].replace("#", "").strip() if lines else f"Article {art_idx}"

                art_num_match = re.search(r"Article\s+(\d+)", header, re.IGNORECASE)
                art_num = art_num_match.group(1) if art_num_match else str(art_idx)
                passage_id = f"{doc_id}-ART-{art_num}"
                citation = f"[{doc_id} - {header}]"

                chunk_record = {
                    "passage_id": passage_id,
                    "document": doc_name,
                    "document_id": doc_id,
                    "document_title": doc_title,
                    "domain": domain,
                    "status": status_val,
                    "version": version_val,
                    "effective_date": eff_date,
                    "section": header,
                    "content": sec_text,
                    "citation": citation,
                }
                self.chunks.append(chunk_record)
                corpus.append(f"{header}\n{sec_text}")
                art_idx += 1

        if corpus:
            self.vectorizer = TfidfVectorizer(stop_words="english")
            self.tfidf_matrix = self.vectorizer.fit_transform(corpus)

    def retrieve(
        self,
        query: str,
        top_k: int = 3,
        domain: str | None = None,
        status_filter: str | None = "ACTIVE",
    ) -> list[dict[str, Any]]:
        """
        Retrieve the top-k most relevant policy chunks for a given query.
        Tries Supabase pgvector first (for cancellation); falls back to local TF-IDF cosine similarity.
        Supports filtering by domain (e.g. 'cancellation', 'security') and status.
        """
        clean_query = query.strip()
        if not clean_query:
            return []

        # 1. Primary: Cloud Supabase pgvector search (when domain is cancellation or unspecified)
        if domain in (None, "cancellation"):
            pgvector_results = _search_supabase_pgvector(clean_query, top_k=top_k)
            if pgvector_results is not None and len(pgvector_results) > 0:
                return pgvector_results

        # 2. Resilient Fallback: Local TF-IDF Cosine Similarity with metadata filtering
        if not self.chunks or self.vectorizer is None or self.tfidf_matrix is None:
            return []

        # Determine candidate indices matching domain & status filter
        candidate_indices = []
        for idx, chunk in enumerate(self.chunks):
            if domain and chunk.get("domain") != domain.lower():
                continue
            if status_filter and status_filter.upper() not in str(chunk.get("status", "")).upper():
                continue
            candidate_indices.append(idx)

        if not candidate_indices:
            return []

        query_vec = self.vectorizer.transform([clean_query])
        sims = cosine_similarity(query_vec, self.tfidf_matrix).flatten()

        # Sort candidate indices by similarity score descending
        candidate_scores = [(idx, float(sims[idx])) for idx in candidate_indices]
        candidate_scores.sort(key=lambda x: x[1], reverse=True)
        top_candidates = candidate_scores[:top_k]

        results: list[dict[str, Any]] = []
        for idx, score in top_candidates:
            chunk = dict(self.chunks[idx])
            chunk["similarity_score"] = round(score, 4)
            chunk["retrieval_method"] = "local_tfidf"
            results.append(chunk)

        return results


# Module-level singleton instance
_kb_instance: PolicyKnowledgeBase | None = None


def get_policy_knowledge_base() -> PolicyKnowledgeBase:
    global _kb_instance
    if _kb_instance is None:
        _kb_instance = PolicyKnowledgeBase()
    return _kb_instance


def retrieve_relevant_policies(
    query: str,
    top_k: int = 3,
    domain: str | None = None,
    status_filter: str | None = "ACTIVE",
) -> list[dict[str, Any]]:
    """
    Public RAG function: returns top-k verified policy chunks for a query.
    Supports optional domain filtering ('cancellation', 'security', 'booking').
    """
    kb = get_policy_knowledge_base()
    return kb.retrieve(query, top_k=top_k, domain=domain, status_filter=status_filter)
