"""
Passenger-facing message catalog (English / Sinhala / Tamil).

Every fixed passenger-facing sentence that is NOT generated by Gemini lives here:
agent-unavailable and validation messages, clarifying questions, the deterministic
fallback used when Gemini is unavailable, and UI action labels. main.py looks
messages up with t(key, language, **params), so the language detected once at the
start of /chat controls every reply path - success, error and fallback alike.

The knowledge base (data/faq_docs/*.md) is deliberately NOT translated: RAG and
agent facts stay in their source language and Gemini writes the answer in the
passenger's language. This catalog only covers the wording around those facts.

English strings are the original wording of the code they replaced.
"""

MESSAGES: dict[str, dict[str, str]] = {
    # ------------------------------------------------ agent / hub problems ---
    "agent_unreachable": {
        "en": "I couldn't reach that service right now. Please try again shortly.",
        "si": "දැනට එම සේවාව අමතන්නට නොහැකි විය. කරුණාකර මද වේලාවකින් නැවත උත්සාහ කරන්න.",
        "ta": "இப்போது அந்தச் சேவையைத் தொடர்பு கொள்ள முடியவில்லை. சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.",
    },
    "agent_rejected": {
        "en": "That service couldn't complete your request right now. Please check the details and try again.",
        "si": "එම සේවාවට දැනට ඔබේ ඉල්ලීම සම්පූර්ණ කළ නොහැකි විය. විස්තර පරීක්ෂා කර නැවත උත්සාහ කරන්න.",
        "ta": "அந்தச் சேவையால் இப்போது உங்கள் கோரிக்கையை நிறைவேற்ற முடியவில்லை. விவரங்களைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.",
    },
    "complaint_failed": {
        "en": "I couldn't log your issue right now.",
        "si": "ඔබේ ගැටලුව දැනට සටහන් කර ගැනීමට නොහැකි විය.",
        "ta": "உங்கள் சிக்கலை இப்போது பதிவு செய்ய முடியவில்லை.",
    },
    "registry_unavailable": {
        "en": "The train registry is temporarily unavailable. Please try again shortly.",
        "si": "දුම්රිය ලේඛනය දැනට තාවකාලිකව නොමැත. කරුණාකර මද වේලාවකින් නැවත උත්සාහ කරන්න.",
        "ta": "ரயில் பதிவேடு தற்போது தற்காலிகமாகக் கிடைக்கவில்லை. சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.",
    },
    # ---------------------------------------- RAG failure / empty retrieval ---
    "rag_error": {
        "en": "I'm having trouble looking that up right now. Please try again in a moment.",
        "si": "දැනට එය සොයා බැලීමේ ගැටලුවක් ඇත. කරුණාකර මද වේලාවකින් නැවත උත්සාහ කරන්න.",
        "ta": "இப்போது அதைத் தேடுவதில் சிக்கல் உள்ளது. சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.",
    },
    "rag_no_chunks": {
        "en": "I don't have that information in my current knowledge base. Could you rephrase, or ask about schedules, fares, delays, or bookings instead?",
        "si": "මගේ දැනට පවතින දැනුම් පදනමේ එම තොරතුරු නොමැත. කරුණාකර වෙනත් ආකාරයකින් අසන්න, නැතහොත් කාලසටහන්, ගාස්තු, ප්‍රමාද හෝ වෙන්කිරීම් ගැන අසන්න.",
        "ta": "என்னிடம் தற்போதுள்ள அறிவுத் தளத்தில் அந்தத் தகவல் இல்லை. வேறு விதமாகக் கேளுங்கள், அல்லது அட்டவணைகள், கட்டணங்கள், தாமதங்கள் அல்லது முன்பதிவு பற்றிக் கேளுங்கள்.",
    },
    # ------------------------------------------------- train id / registry ---
    "train_id_needed_info": {
        "en": "Please provide a train ID so I can check the canonical train registry.",
        "si": "දුම්රිය ලේඛනයේ පරීක්ෂා කිරීමට කරුණාකර දුම්රියේ හැඳුනුම් අංකය ලබා දෙන්න.",
        "ta": "ரயில் பதிவேட்டில் சரிபார்க்க, தயவுசெய்து ரயில் அடையாள எண்ணை வழங்கவும்.",
    },
    "train_id_needed_status": {
        "en": "Please provide a train ID (e.g. PM-4082) so I can check its status.",
        "si": "තත්ත්වය පරීක්ෂා කිරීමට කරුණාකර දුම්රියේ හැඳුනුම් අංකය (උදා: PM-4082) ලබා දෙන්න.",
        "ta": "நிலையைச் சரிபார்க்க, தயவுசெய்து ரயில் அடையாள எண்ணை (எ.கா. PM-4082) வழங்கவும்.",
    },
    "delay_need_train_id": {
        "en": "provide a train ID so Operations can validate it.",
        "si": "දුම්රියේ හැඳුනුම් අංකය (උදා: PM-4082) ලබා දෙන්න; එවිට මෙහෙයුම් අංශයට එය තහවුරු කළ හැකිය.",
        "ta": "ரயில் அடையாள எண்ணை (எ.கா. PM-4082) வழங்கவும்; அப்போது செயல்பாட்டுப் பிரிவு அதைச் சரிபார்க்க முடியும்.",
    },
    "train_not_found_registry": {
        "en": "{train_id} is not registered in the canonical train registry.",
        "si": "{train_id} දුම්රිය ලේඛනයේ ලියාපදිංචි වී නොමැත.",
        "ta": "{train_id} ரயில் பதிவேட்டில் பதிவு செய்யப்படவில்லை.",
    },
    "train_not_found_status": {
        "en": "{train_id} is not a recognised train service.",
        "si": "{train_id} හඳුනාගත් දුම්රිය සේවාවක් නොවේ.",
        "ta": "{train_id} அங்கீகரிக்கப்பட்ட ரயில் சேவை அல்ல.",
    },
    "route_found": {
        "en": "I found {n} train service(s) from {origin} to {destination}:",
        "si": "{origin} සිට {destination} දක්වා දුම්රිය සේවා {n} ක් මට හමු විය:",
        "ta": "{origin} இலிருந்து {destination} வரை {n} ரயில் சேவை(கள்) கண்டறியப்பட்டன:",
    },
    "route_none": {
        "en": "I couldn't find a shared train service from {origin} to {destination}.",
        "si": "{origin} සිට {destination} දක්වා පොදු දුම්රිය සේවාවක් මට සොයාගත නොහැකි විය.",
        "ta": "{origin} இலிருந்து {destination} வரை பகிரப்பட்ட ரயில் சேவை எதுவும் கிடைக்கவில்லை.",
    },
    # ------------------------------------------------------------ train info ---
    "train_info_main": {
        "en": "{name} ({train_id}) is {state}. Route: {route}. Maintenance status: {maintenance}.",
        "si": "{name} ({train_id}) දුම්රිය {state}. මාර්ගය: {route}. නඩත්තු තත්ත්වය: {maintenance}.",
        "ta": "{name} ({train_id}) {state}. வழித்தடம்: {route}. பராமரிப்பு நிலை: {maintenance}.",
    },
    "train_state_active": {"en": "active", "si": "ක්‍රියාත්මකයි", "ta": "இயக்கத்தில் உள்ளது"},
    "train_state_inactive": {"en": "inactive", "si": "ක්‍රියාත්මක නොවේ", "ta": "இயக்கத்தில் இல்லை"},
    "route_not_recorded": {
        "en": "route not recorded",
        "si": "මාර්ගය සටහන් කර නැත",
        "ta": "வழித்தடம் பதிவு செய்யப்படவில்லை",
    },
    "train_next_service": {
        "en": " Next recorded service: {origin} to {destination} on {date} at {time}.",
        "si": " ඊළඟ සටහන් කළ සේවාව: {origin} සිට {destination} දක්වා, {date} දින {time} ට.",
        "ta": " அடுத்த பதிவு செய்யப்பட்ட சேவை: {origin} இலிருந்து {destination} வரை, {date} அன்று {time} மணிக்கு.",
    },
    # ------------------------------------------------------- train status (M4) ---
    "train_status_failed": {
        "en": "I couldn't check the train status right now. Please try again shortly.",
        "si": "දුම්රියේ තත්ත්වය දැනට පරීක්ෂා කළ නොහැකි විය. කරුණාකර මද වේලාවකින් නැවත උත්සාහ කරන්න.",
        "ta": "ரயிலின் நிலையை இப்போது சரிபார்க்க முடியவில்லை. சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.",
    },
    "train_status_maint": {
        "en": "Train {train_id} is currently under maintenance and may not be in service. Reason: {reason}.{eta} We apologise for the inconvenience.",
        "si": "{train_id} දුම්රිය දැනට නඩත්තු කටයුතු යටතේ පවතින අතර සේවයේ නොයෙදෙන්නට පුළුවන. හේතුව: {reason}.{eta} අපහසුතාවට කනගාටුයි.",
        "ta": "{train_id} ரயில் தற்போது பராமரிப்பில் உள்ளது; சேவையில் இல்லாமல் இருக்கலாம். காரணம்: {reason}.{eta} சிரமத்திற்கு வருந்துகிறோம்.",
    },
    "train_status_eta": {
        "en": " Expected back in service by {eta}.",
        "si": " {eta} වන විට නැවත සේවයට පැමිණීමට අපේක්ෂිතයි.",
        "ta": " {eta} அளவில் மீண்டும் சேவைக்கு வர எதிர்பார்க்கப்படுகிறது.",
    },
    "train_status_clear": {
        "en": "Train {train_id} has no active maintenance issues and is cleared for service.",
        "si": "{train_id} දුම්රියට සක්‍රීය නඩත්තු ගැටලු නොමැති අතර සේවයට අනුමත කර ඇත.",
        "ta": "{train_id} ரயிலுக்குச் செயலில் உள்ள பராமரிப்புச் சிக்கல்கள் இல்லை; சேவைக்குத் தயாராக உள்ளது.",
    },
    # --------------------------------------------- delay (Operations Agent) ---
    "delay_headline_hist": {
        "en": "Expected delay: {delay} minutes (based on this train's recorded history, not a live status).",
        "si": "අපේක්ෂිත ප්‍රමාදය: මිනිත්තු {delay} ක් (මෙම දුම්රියේ වාර්තා කළ ඉතිහාසය අනුව; සජීවී තත්ත්වයක් නොවේ).",
        "ta": "எதிர்பார்க்கப்படும் தாமதம்: {delay} நிமிடங்கள் (இந்த ரயிலின் பதிவு செய்யப்பட்ட வரலாற்றின் அடிப்படையில்; நேரடி நிலை அல்ல).",
    },
    "delay_headline_est": {
        "en": "Expected delay: {delay} minutes (an estimate, not a live status).",
        "si": "අපේක්ෂිත ප්‍රමාදය: මිනිත්තු {delay} ක් (ඇස්තමේන්තුවක්; සජීවී තත්ත්වයක් නොවේ).",
        "ta": "எதிர்பார்க்கப்படும் தாமதம்: {delay} நிமிடங்கள் (மதிப்பீடு; நேரடி நிலை அல்ல).",
    },
    "delay_record": {
        "en": "Historical record: {reason}.",
        "si": "ඉතිහාස වාර්තාව: {reason}.",
        "ta": "வரலாற்றுப் பதிவு: {reason}.",
    },
    "delay_reason": {"en": "Reason: {reason}.", "si": "හේතුව: {reason}.", "ta": "காரணம்: {reason}."},
    "delay_similar": {
        "en": "Similar past incident (historical, not current): {similar}.",
        "si": "සමාන අතීත සිදුවීමක් (ඉතිහාසය, වර්තමානය නොවේ): {similar}.",
        "ta": "ஒத்த கடந்த சம்பவம் (வரலாறு, தற்போதையது அல்ல): {similar}.",
    },
    "delay_maint": {
        "en": "Maintenance update: {reason}.",
        "si": "නඩත්තු යාවත්කාලීනය: {reason}.",
        "ta": "பராமரிப்பு தகவல்: {reason}.",
    },
    "delay_maint_note": {
        "en": "Maintenance work is reported on this train.",
        "si": "මෙම දුම්රිය සම්බන්ධයෙන් නඩත්තු කටයුතු වාර්තා වී ඇත.",
        "ta": "இந்த ரயில் தொடர்பாக பராமரிப்புப் பணிகள் பதிவாகியுள்ளன.",
    },
    "delay_maint_eta": {
        "en": " Expected back in service by {eta}.",
        "si": " {eta} වන විට නැවත සේවයට පැමිණීමට අපේක්ෂිතයි.",
        "ta": " {eta} அளவில் மீண்டும் சேவைக்கு வர எதிர்பார்க்கப்படுகிறது.",
    },
    # ------------------------------------------------------------ complaint ---
    "complaint_logged": {
        "en": "Your issue has been logged and passed to the maintenance team. (Ticket: {ticket})",
        "si": "ඔබේ ගැටලුව සටහන් කර නඩත්තු කණ්ඩායමට යොමු කරන ලදී. (යොමු අංකය: {ticket})",
        "ta": "உங்கள் சிக்கல் பதிவு செய்யப்பட்டு பராமரிப்புக் குழுவிற்கு அனுப்பப்பட்டுள்ளது. (குறிப்பு எண்: {ticket})",
    },
    # -------------------------------------------------------------- booking ---
    "booking_found": {
        "en": "I found your booking request from **{origin}** to **{destination}**{date_part}. Click the button below to proceed to the reservation desk with these details pre-filled.",
        "si": "ඔබේ වෙන්කිරීමේ ඉල්ලීම **{origin}** සිට **{destination}** දක්වා{date_part} සොයාගත්තෙමි. මෙම විස්තර සමඟ වෙන්කිරීමේ අංශයට යාමට පහත බොත්තම ඔබන්න.",
        "ta": "உங்கள் முன்பதிவு கோரிக்கையை **{origin}** இலிருந்து **{destination}** வரை{date_part} கண்டறிந்தேன். இந்த விவரங்களுடன் முன்பதிவு மேசைக்குச் செல்ல கீழே உள்ள பொத்தானை அழுத்தவும்.",
    },
    "booking_date_part": {
        "en": " on **{date}**",
        "si": " **{date}** දින",
        "ta": " **{date}** அன்று",
    },
    "booking_open_desk": {
        "en": "I can help you book a train ticket! Click the button below to open the booking desk and select your route and date.",
        "si": "දුම්රිය ටිකට් පතක් වෙන්කරගැනීමට මට ඔබට උදව් කළ හැක! ඔබේ මාර්ගය සහ දිනය තෝරාගැනීමට පහත බොත්තම ඔබා වෙන්කිරීමේ අංශය විවෘත කරන්න.",
        "ta": "ரயில் டிக்கெட்டை முன்பதிவு செய்ய நான் உதவ முடியும்! உங்கள் வழித்தடத்தையும் தேதியையும் தேர்ந்தெடுக்க கீழே உள்ள பொத்தானை அழுத்தி முன்பதிவு மேசையைத் திறக்கவும்.",
    },
    # Missing-station questions. The known station is never guessed into the wrong slot.
    "booking_ask_origin": {
        "en": "Which station would you like to travel from to {destination}?",
        "si": "ඔබ කොතැනින් {destination}ට යාමට ටිකට් වෙන්කරගන්නද?",
        "ta": "நீங்கள் எந்த நிலையத்திலிருந்து பயணிக்க விரும்புகிறீர்கள்? (சேருமிடம்: {destination})",
    },
    "booking_ask_destination": {
        "en": "Which station would you like to travel to from {origin}?",
        "si": "ඔබ {origin} සිට කොතැනට යාමට ටිකට් වෙන්කරගන්නද?",
        "ta": "நீங்கள் எந்த நிலையத்திற்குப் பயணிக்க விரும்புகிறீர்கள்? (புறப்படும் நிலையம்: {origin})",
    },
    "booking_ask_both": {
        "en": "Which stations would you like to travel from and to?",
        "si": "ඔබ කොතැනින් කොතැනට යාමට ටිකට් වෙන්කරගන්නද?",
        "ta": "நீங்கள் எந்த நிலையத்திலிருந்து எந்த நிலையத்திற்குப் பயணிக்க விரும்புகிறீர்கள்?",
    },
    "label_continue_booking": {
        "en": "Continue to Booking ➔",
        "si": "වෙන්කිරීමට ඉදිරියට යන්න ➔",
        "ta": "முன்பதிவைத் தொடரவும் ➔",
    },
    # --------------------------------------------------------- cancellation ---
    "cancel_prepared": {
        "en": "I have prepared your cancellation request for booking **{ref}** with reason: *\"{reason}\"*. Please review the confirmation card below and click **Send Cancellation Request**.",
        "si": "**{ref}** වෙන්කිරීම සඳහා ඔබේ අවලංගු කිරීමේ ඉල්ලීම මම සකස් කළෙමි. හේතුව: *\"{reason}\"*. පහත තහවුරු කිරීමේ කාඩ්පත පරීක්ෂා කර **අවලංගු කිරීමේ ඉල්ලීම යවන්න** ඔබන්න.",
        "ta": "**{ref}** முன்பதிவுக்கான ரத்து கோரிக்கையைத் தயார் செய்துள்ளேன். காரணம்: *\"{reason}\"*. கீழே உள்ள உறுதிப்படுத்தல் அட்டையைச் சரிபார்த்து **ரத்து கோரிக்கையை அனுப்பு** என்பதை அழுத்தவும்.",
    },
    "cancel_need_ref": {
        "en": "Please tell me your booking reference (it looks like RS-12345) so I can prepare the cancellation request. Reason given: *\"{reason}\"*.",
        "si": "අවලංගු කිරීමේ ඉල්ලීම සකස් කිරීමට කරුණාකර ඔබේ වෙන්කිරීමේ යොමු අංකය (RS-12345 වැනි) ලබා දෙන්න. ලබා දුන් හේතුව: *\"{reason}\"*.",
        "ta": "ரத்து கோரிக்கையைத் தயார் செய்ய, தயவுசெய்து உங்கள் முன்பதிவு குறிப்பு எண்ணை (RS-12345 போன்றது) வழங்கவும். கொடுக்கப்பட்ட காரணம்: *\"{reason}\"*.",
    },
    "no_reason_provided": {
        "en": "No reason provided",
        "si": "හේතුවක් සඳහන් කර නැත",
        "ta": "காரணம் குறிப்பிடப்படவில்லை",
    },
    "label_send_cancellation": {
        "en": "Send Cancellation Request ➔",
        "si": "අවලංගු කිරීමේ ඉල්ලීම යවන්න ➔",
        "ta": "ரத்து கோரிக்கையை அனுப்பு ➔",
    },
}


def t(key: str, language: str, **params) -> str:
    """Look up a message in the passenger's language (English if that language
    or key has no entry) and fill in its parameters."""
    entry = MESSAGES[key]
    text = entry.get(language) or entry["en"]
    return text.format(**params) if params else text
